--Q1 What is the total revenue generated by male vs female customers
select gender, sum(purchase_amount) as Revenue 
from customer
group by gender

--Q2 Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied ='Yes' and purchase_amount>=(select avg(purchase_amount)
from customer)

--Q3 Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Review Rating"
from customer
group by item_purchased
order by "Average Review Rating" desc 
limit 5

--Q4 Compare the average purchase amount between standard and express shipping
select shipping_type,round(avg(purchase_amount),2)
from customer
where shipping_type in('Express','Standard')
group by shipping_type
order by round(avg(purchase_amount),2) desc

--Q5 Do subscribe customers spend more? Compare average spend and total revenue 
--between subscriber and non subscriber
select subscription_status, round(avg(purchase_amount),2) as "Average Spent",sum(purchase_amount) as "Total revenue",
count(*) as "Total customers"
from customer
group by subscription_status

--Q6 Which 5 products have the highest percentage of purchases 	with discount applied?
select item_purchased, round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--Q7 Segement customers who are New, Returning, Loyal based on their total
--number of previous purchases, and show the count of each segement
with customer_type as(
select customer_id,previous_purchases,
case 
	when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment,count(*)
from customer_type
group by customer_segment

--Q8 What are the top 3 most purchased products within each category?
with item_counts as (
select category,item_purchased, 
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
select *
from item_counts
where item_rank<=3

--Q9 Are customers who are repeat buyers (more than 5 previous purchases) likely to subscibe?
select subscription_status,count(*) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10 What is the revenue contribution from each group
select age_group,sum(purchase_amount) as "Total revenue"
from customer
group by age_group
order by "Total revenue" desc
